# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_rgig1 <- function(lambda, chi, psi) {
    .Call(`_drbart_do_rgig1`, lambda, chi, psi)
}

gig_norm <- function(lambda, chi, psi) {
    .Call(`_drbart_gig_norm`, lambda, chi, psi)
}

dmixnorm0 <- function(x, logprob, mu, sd) {
    .Call(`_drbart_dmixnorm0`, x, logprob, mu, sd)
}

pmixnorm0 <- function(x, logprob, mu, sd) {
    .Call(`_drbart_pmixnorm0`, x, logprob, mu, sd)
}

dmixnorm <- function(x, logprob, mu, sd) {
    .Call(`_drbart_dmixnorm`, x, logprob, mu, sd)
}

pmixnorm <- function(x, logprob, mu, sd) {
    .Call(`_drbart_pmixnorm`, x, logprob, mu, sd)
}

dmixnorm0_post <- function(x, mus, sd, logprobs) {
    .Call(`_drbart_dmixnorm0_post`, x, mus, sd, logprobs)
}

pmixnorm0_post <- function(x, mus, sd, logprobs) {
    .Call(`_drbart_pmixnorm0_post`, x, mus, sd, logprobs)
}

dmixnorm_post <- function(x, mus, sds, logprobs) {
    .Call(`_drbart_dmixnorm_post`, x, mus, sds, logprobs)
}

pmixnorm_post <- function(x, mus, sds, logprobs) {
    .Call(`_drbart_pmixnorm_post`, x, mus, sds, logprobs)
}

drbartRcppClean <- function(y_, x_, xpred_, xinfo_list, burn, nd, thin, printevery, m, alpha, beta, lambda, nu, kfac, trunc_below, treef_name_) {
    .Call(`_drbart_drbartRcppClean`, y_, x_, xpred_, xinfo_list, burn, nd, thin, printevery, m, alpha, beta, lambda, nu, kfac, trunc_below, treef_name_)
}

